# Generated by Django 3.0.8 on 2021-04-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud_profile',
            fields=[
                ('stud_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=50)),
                ('stud_email', models.CharField(max_length=50)),
                ('stud_college', models.CharField(max_length=50)),
                ('stud_address', models.CharField(max_length=100)),
                ('stud_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stud_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_course', models.CharField(max_length=80)),
                ('stud_domain', models.CharField(max_length=80)),
                ('stud_fees', models.IntegerField()),
                ('stud_batch', models.IntegerField()),
                ('stud_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.stud_profile')),
            ],
        ),
    ]
