# Generated by Django 3.0.8 on 2021-04-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stud_details',
            new_name='stud_detail',
        ),
    ]
