# Generated by Django 3.0.8 on 2021-04-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_auto_20210413_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud_detail',
            old_name='stud_id',
            new_name='Stud_id',
        ),
    ]
