# Generated by Django 3.0.8 on 2021-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_auto_20210419_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_profile',
            name='stud_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
