# Generated by Django 3.0.8 on 2021-04-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_auto_20210423_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer_profile',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('tr_name', models.CharField(max_length=50)),
                ('tr_username', models.CharField(max_length=50)),
                ('tr_email', models.CharField(max_length=50)),
                ('tr_college', models.CharField(max_length=50)),
                ('tr_address', models.CharField(max_length=100)),
                ('tr_phone', models.IntegerField()),
                ('tr_passwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_detail',
            fields=[
                ('Tr_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Admin.Trainer_profile')),
                ('task_assigned', models.CharField(max_length=80)),
                ('task_completed', models.CharField(max_length=80)),
                ('task_assgn_date', models.DateTimeField(blank=True)),
                ('task_complete_date', models.DateTimeField(blank=True)),
                ('tr_batch', models.IntegerField()),
            ],
        ),
    ]
