# Generated by Django 3.0.8 on 2021-04-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_trainer_detail_trainer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer_profile',
            name='tr_college',
        ),
        migrations.RemoveField(
            model_name='trainer_profile',
            name='tr_passwd',
        ),
        migrations.RemoveField(
            model_name='trainer_profile',
            name='tr_username',
        ),
    ]
