# Generated by Django 3.0.8 on 2021-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_auto_20210425_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_profile',
            name='stud_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
