# Generated by Django 3.0.8 on 2021-04-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_auto_20210427_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_profile',
            name='tr_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
