# Generated by Django 3.0.8 on 2021-04-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_auto_20210427_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_detail',
            name='Tr_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Admin.Trainer_profile'),
        ),
        migrations.AlterField(
            model_name='trainer_profile',
            name='tr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
