# Generated by Django 3.0.8 on 2021-04-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_auto_20210427_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_profile',
            name='tr_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
