# Generated by Django 3.0.8 on 2021-04-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_auto_20210428_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_detail',
            name='Tr_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Admin.Trainer_profile'),
        ),
    ]
