# Generated by Django 3.0.8 on 2021-04-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_auto_20210428_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_profile',
            name='tr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
