# Generated by Django 3.0.8 on 2021-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_auto_20210428_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_profile',
            name='stud_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
