# Generated by Django 3.0.8 on 2021-04-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0034_auto_20210428_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer_profile',
            fields=[
                ('Rf_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Rf_name', models.CharField(max_length=50)),
                ('Rf_email', models.CharField(max_length=50)),
                ('Rf_address', models.CharField(max_length=100)),
                ('Rf_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Referrer_leads',
            fields=[
                ('RF_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Admin.Referrer_profile')),
                ('Rf_stud_name', models.CharField(max_length=80)),
                ('Rf_stud_college', models.CharField(max_length=80)),
                ('Rf_stud_phone', models.IntegerField()),
            ],
        ),
    ]
