# Generated by Django 3.0.8 on 2021-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0035_referrer_leads_referrer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer_profile',
            name='Rf_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stud_profile',
            name='stud_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainer_profile',
            name='tr_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
