# Generated by Django 3.0.8 on 2021-05-03 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0037_auto_20210503_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer_profile',
            name='Rf_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stud_profile',
            name='stud_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainer_detail',
            name='Tr_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Admin.Trainer_profile'),
        ),
    ]
