# Generated by Django 3.0.8 on 2021-05-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0041_auto_20210503_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_profile',
            name='stud_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
